PUT file://environment.yml @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://*.py @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://components/*.py @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code/components OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://pages/*.py @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code/pages OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://utils/*.py @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code/utils OVERWRITE = TRUE AUTO_COMPRESS = FALSE;
PUT file://utils/storage/*.py @HACKATHON_GLACIAL_RIDERS.PUBLIC.app_code/utils/storage OVERWRITE = TRUE AUTO_COMPRESS = FALSE;